services:
  db:
    container_name: mysql-bs
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'bookscapedb'
      MYSQL_USER: 'bookscape'
      MYSQL_PASSWORD: 'bookscape!'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - spring-demo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    links:
      - db:mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    networks:
      - spring-demo

  mail-dev:
    container_name: mail-dev-bs
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  my-db:
    driver: local
