import { IconDefinition } from '@fortawesome/fontawesome-svg-core';
import {
  faCartShopping,
  faCheck,
  faShoppingCart,
  faTruckFast,
  faUser,
  faXmark,
  faBook,
  faUserCheck,
  faCode,
  faCircleInfo,
  faListCheck,
  faHeart,
  faEdit,
  faShareNodes,
  faArchive,
  faStar,
  faStarHalf,
  faAnglesLeft,
  faAnglesRight,
  faAngleLeft,
  faAngleRight,
  faChevronLeft,
  faChevronRight,
  faHome, faPlus, faPaperPlane, faDoorOpen, faSearch,
} from '@fortawesome/free-solid-svg-icons'; // Solid icons
import {
  faFacebook,
  faTwitter,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons'; // Brand icons
import { faCircleCheck } from '@fortawesome/free-regular-svg-icons'; // Regular icons

export const fontAwesomeIcons: IconDefinition[] = [
  faUser,
  faCartShopping,
  faTruckFast,
  faYoutube,
  faFacebook,
  faTwitter,
  faXmark,
  faCheck,
  faShoppingCart,
  faCircleCheck,faUserCheck,
  faCode,
  faUser,
  faCircleInfo,
  faListCheck,
  faHeart,
  faEdit,
  faShareNodes,
  faArchive,
  faBook,
  faStar,
  faStarHalf,
  faAnglesLeft,
  faAnglesRight,
  faAngleLeft,
  faAngleRight,
  faChevronRight,
  faBook,
  faHeart,
  faTruckFast,
  faListCheck,
  faHome,
  faPlus,
  faPaperPlane,
  faCircleCheck,
  faDoorOpen,
  faSearch
];
