/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BorrowedBookDto } from '../models/borrowed-book-dto';
export interface PageResponseBorrowedBookDto {
  content?: Array<BorrowedBookDto>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
